"use client";
import checkIsPublicRoute from '@/utils/checkIsPublicRoute'
import './globals.css'
// import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import { usePathname } from 'next/navigation'
import PrivateRoute from '@/components/PrivateRoute'

const inter = Inter({ subsets: ['latin'] })

// export const metadata: Metadata = {
//   title: 'Create Next App',
//   description: 'Generated by create next app',
// }

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {

  const pathName: string = usePathname();

  const isPublicRoute: boolean = checkIsPublicRoute(pathName);

  return (
    <html lang="pt-BR">
      <body className={inter.className}>
        {isPublicRoute && children}
        {!isPublicRoute && (
          <PrivateRoute>
            {children}
          </PrivateRoute>
        )}
      </body>
    </html>
  )
}
